# Rebuild catalogue from maintained metadata
file(READ "${CMAKE_CURRENT_LIST_DIR}/../data/dev-vehicles.json" DEV_VEHICLES_JSON)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${CMAKE_CURRENT_LIST_DIR}/../data/dev-vehicles.json")
string(JSON DEV_VEHICLES_COUNT LENGTH "${DEV_VEHICLES_JSON}" vehicles)
math(EXPR DEV_VEHICLES_LAST "${DEV_VEHICLES_COUNT} - 1")
set(DEV_VEHICLES_C "/* Generated from data/dev-vehicles.json. Do not edit. */\n")
foreach(i RANGE 0 ${DEV_VEHICLES_LAST})
    foreach(field name template faction kind template_hash model_hash radius bottom height half_width half_length source)
        string(JSON value_${field} GET "${DEV_VEHICLES_JSON}" vehicles ${i} ${field})
        string(REPLACE "\\" "\\\\" value_${field} "${value_${field}}")
        string(REPLACE "\"" "\\\"" value_${field} "${value_${field}}")
    endforeach()
    if(NOT value_source MATCHES "^template_vehicles(_ch[1-4])?[.]lyr$")
        message(FATAL_ERROR "Unexpected developer vehicle template layer: ${value_source}")
    endif()
    string(REGEX REPLACE "[.]lyr$" "" value_asset_list "${value_source}")
    string(APPEND DEV_VEHICLES_C "{\"${value_name}\",\"${value_template}\",\"${value_faction}\",\"${value_kind}\",${value_template_hash}u,${value_model_hash}u,${value_radius},${value_bottom},${value_height},${value_half_width},${value_half_length},\"${value_asset_list}\"},\n")
endforeach()
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/dev_vehicle_catalog.inc" "${DEV_VEHICLES_C}")

# Troop metadata uses the same spawn footprint record, with its own UI category.
file(READ "${CMAKE_CURRENT_LIST_DIR}/../data/dev-troops.json" DEV_TROOPS_JSON)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${CMAKE_CURRENT_LIST_DIR}/../data/dev-troops.json")
string(JSON DEV_TROOPS_COUNT LENGTH "${DEV_TROOPS_JSON}" troops)
math(EXPR DEV_TROOPS_LAST "${DEV_TROOPS_COUNT} - 1")
set(DEV_TROOPS_C "/* Generated from data/dev-troops.json. Do not edit. */\n")
foreach(i RANGE 0 ${DEV_TROOPS_LAST})
    foreach(field name template faction kind template_hash model_hash radius bottom height half_width half_length)
        string(JSON value_${field} GET "${DEV_TROOPS_JSON}" troops ${i} ${field})
    endforeach()
    string(APPEND DEV_TROOPS_C "{\"${value_name}\",\"${value_template}\",\"${value_faction}\",\"${value_kind}\",${value_template_hash}u,${value_model_hash}u,${value_radius},${value_bottom},${value_height},${value_half_width},${value_half_length},\"template_humans\"},\n")
endforeach()
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/dev_troop_catalog.inc" "${DEV_TROOPS_C}")
