"""Pack supplied prompt artwork into deterministic, lossless BGRA runs."""
from pathlib import Path
import re
import av
import cv2
import numpy as np
ROOT=Path(__file__).resolve().parents[2]
SRC=ROOT/'ports/mercenaries/assets/prompts'
OUT=ROOT/'ports/mercenaries/src/prompt_assets.inc'
def read(p):
    with av.open(str(p)) as c:return next(c.decode(video=0)).to_ndarray(format='bgra')
def fit(im):
    h,w=im.shape[:2]; scale=min(60/w,60/h); nw,nh=max(1,round(w*scale)),max(1,round(h*scale))
    f=im.astype(np.float32)/255;f[:,:,:3]*=f[:,:,3:4]
    f=cv2.resize(f,(nw,nh),interpolation=cv2.INTER_AREA if scale<1 else cv2.INTER_LINEAR)
    f[:,:,:3]/=np.maximum(f[:,:,3:4],1/255)
    out=np.zeros((64,64,4),np.uint8);out[(64-nh)//2:(64-nh)//2+nh,(64-nw)//2:(64-nw)//2+nw]=np.rint(f*255).clip(0,255).astype(np.uint8)
    return out
items=[]
for p in sorted(SRC.glob('keyboard*.png'),key=lambda p:int(re.search(r'_g(\d+)_',p.name)[1])):
    items.append(('KEY_'+re.search(r'_g(\d+)_',p.name)[1],fit(read(p))))
for family,folder in [('PS',SRC),('XBOX',SRC/'xbox')]:
    buttons=read(folder/'buttons.tga'); buttons2=read(folder/'buttons2.tga');markers=read(folder/'markers.tga')
    # Original Xbox atlas cells differ from the supplied PlayStation atlas.
    cells={'Y':(0,0),'B':(1,0),'X':(0,1),'A':(1,1),'LB':(2,0),'RB':(3,0),'LT':(2,1),'RT':(3,1)} if family=='PS' else {'Y':(0,0),'B':(1,0),'X':(0,1),'A':(1,1),'LT':(2,0),'RT':(3,0),'LB':(2,1),'RB':(3,1)}
    for name,(x,y) in cells.items():items.append((family+'_'+name,fit(buttons[y*32:y*32+32,x*32:x*32+32])))
    for name,x,y in [('DPAD',0,0),('START',32,0),('BACK',0,32)]:items.append((family+'_'+name,fit(buttons2[y:y+32,x:x+32])))
    for name,x in [('LS',32),('RS',48)]:items.append((family+'_'+name,fit(markers[48:64,x:x+16])))
# Directional bindings need their direction as well as the stick/pad name.
original=dict(items)
for family in ('PS','XBOX'):
    for group in ('DPAD','LS','RS'):
        for direction,arrow in [('UP',1412),('DOWN',1413),('LEFT',1414),('RIGHT',1415)]:
            base=original[family+'_'+group].copy()
            small=cv2.resize(original['KEY_'+str(arrow)],(30,30),interpolation=cv2.INTER_AREA)
            # Keep the supplied direction key shape distinct from the stick.
            base[34:64,34:64]=small
            items.append((family+'_'+group+'_'+direction,base))
items.append(('BLANK',np.zeros((64,64,4),np.uint8)))
runs=[];records=[]
for name,im in items:
    pixels=im.view('<u4').reshape(-1);start=len(runs);i=0
    while i<len(pixels):
        j=i+1
        while j<len(pixels) and pixels[j]==pixels[i] and j-i<65535:j+=1
        runs.append((j-i,int(pixels[i])));i=j
    records.append((name,start,len(runs)-start))
lines=['/* Generated by tools/recomp/build_prompt_assets.py; supplied artwork. */','enum {']
lines += [' PROMPT_'+n+' = '+str(i)+',' for i,(n,_,_) in enumerate(records)]
lines+=[' PROMPT_ASSET_COUNT='+str(len(records))+' };','typedef struct { unsigned short count; unsigned int bgra; } PromptRun;','static const PromptRun prompt_runs[]={']
lines += [' {'+str(n)+',0x%08Xu},'%v for n,v in runs]
lines+=['};','static const struct { unsigned int start,count; } prompt_asset_runs[]={']
lines += [' {'+str(s)+','+str(c)+'},' for _,s,c in records]
lines+=['};']
OUT.write_text('\n'.join(lines)+'\n')
print(f'{len(records)} assets, {len(runs)} runs, {OUT.stat().st_size} bytes')
