"""Regenerate developer troop data from the user's retail DATAxbox/assets.dsk.

Menu labels, role selection, base-template choices and generic spawn padding are
project UI/placement policy. Models and applied role properties come from the
named retail records below. No editor data or existing catalogue is read.
"""
from pathlib import Path
import argparse
import hashlib
import json
import sys

ROOT=Path(__file__).resolve().parents[2]
sys.path.insert(0,str(ROOT))
from tools.diagnostics.inspect_retail_templates import template_instances,hash_string

FACTIONS={'allies':'Allied Nations','china':'Chinese','nk':'North Korean',
          'mafia':'Russian Mafia','sk':'South Korean'}
ROLES={'heavy','officer','pilot','soldier','soldier_easy','elite'}
# Retail profiles chosen to preserve the established menu roles, without loading
# their mission layers into gameplay. Each selection is checked for uniqueness.
VARIANTS=[
    ('nw_mafia4','template_mafia4_heavy','template_mafia_soldier','Heavy'),
    ('nw_poi_yongbyon-mafia6','template_ybd_mafia_officer01','template_mafia_soldier','Officer'),
    ('nw_poi_sinuiju_traffic','template_sdk_sk_heavy','template_sk_soldier','Heavy'),
    ('admnd_island02','template_supergunner','template_nk_elite','Radiation Soldier'),
]
GEOMETRIES={'mafia_hum_heavysoldier','mafia_hum_officer',
            'sk_hum_heavysoldier','nk_hum_radiationsoldier'}
PROPERTIES=['geometryfile','displayname','weapon_a_template','secondaryweapon_a_template',
            'spawnondeath','factionvalue','ai_accuracy','visionfactor']


def catalog_row(record, role, model=None):
    props=record['properties'];faction=props['faction'].lower()
    geometry=model or props['geometryfile']
    result={'name':FACTIONS[faction]+' '+role,'template':record['template'],
            'faction':faction,'kind':'troop','template_hash':record['template_hash'],
            'model_hash':hash_string(geometry),
            # Deliberate generic human spawn capsule/clearance policy, not a
            # claim that these numbers reconstruct a retail model bounding box.
            'radius':0.6,'bottom':0,'height':1.8,'half_width':0.3,'half_length':0.3,
            'source':'template_humans.lyr'}
    if model:result['variant_model']=model
    return result


def extract(data):
    archive=Path(data)/'assets.dsk'
    base={r['template']:r for r in template_instances(archive,'template_humans')}
    rows=[];evidence=[]
    for name,record in base.items():
        pieces=name.split('_',2)
        if len(pieces)!=3 or pieces[0]!='template':continue
        _,faction,role=pieces
        if faction not in FACTIONS or role not in ROLES:continue
        if record['properties'].get('objecttype','').lower()!='human':
            raise ValueError('Selected troop is not a human: '+name)
        rows.append(catalog_row(record,role.replace('_',' ').title()))
        evidence.append({'menu':rows[-1]['name'],'layer':record['layer'],'object':name,
                         'record_index':record['record_index']})
    selected={(layer,name):[] for layer,name,_,_ in VARIANTS}
    for record in template_instances(archive,'',GEOMETRIES):
        key=(record['layer'],record['template'])
        if key in selected:selected[key].append(record)
    variants=[]
    for layer,name,base_name,role in VARIANTS:
        records=selected[(layer,name)]
        if len(records)!=1:raise ValueError('Missing or ambiguous retail profile: '+name)
        record=records[0];props=record['properties'];shared=base[base_name]
        if props['faction'].lower()!=shared['properties']['faction'].lower():
            raise ValueError('Variant faction mismatch')
        values=[props[key].lower() for key in PROPERTIES]
        values += [base_name,shared['properties']['geometryfile'],props['hitpoints']]
        for field in ['armortype','animationtable']:
            value=props[field]
            refresh = props['geometryfile']=='sk_hum_heavysoldier'
            values.append(None if not refresh and value.lower()==shared['properties'][field].lower() else value)
        variants.append(values)
        rows.append(catalog_row(shared,role,props['geometryfile']))
        evidence.append({'menu':rows[-1]['name'],'layer':layer,'object':name,
                         'record_index':record['record_index'],
                         'base_template':base_name})
    rows.sort(key=lambda row:row['name'])
    header='/* Generated by extract_dev_troop_catalog.py from retail profiles. */\n'
    header+='\n'.join('    {'+','.join('NULL' if v is None else json.dumps(v) for v in row)+'},'
                       for row in variants)+'\n'
    metadata={'provenance':'Regenerated from retail assets.dsk by extract_dev_troop_catalog.py. '
              'Menu labels, selected roles, base-template mapping and generic spawn clearance '
              'are project policy. See docs/runtime/retail-troop-evidence.md.', 'troops':rows}
    manifest={'archive_sha256':hashlib.sha256(archive.read_bytes()).hexdigest(),
              'records':evidence,'variant_fields':PROPERTIES+
              ['base_template','base_model','hitpoints','armortype_override','animationtable_override']}
    return metadata,header,manifest


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('data',type=Path)
    parser.add_argument('--catalog',required=True,type=Path)
    parser.add_argument('--variants',required=True,type=Path)
    parser.add_argument('--evidence',required=True,type=Path)
    args=parser.parse_args();catalog,header,evidence=extract(args.data)
    args.catalog.write_text(json.dumps(catalog,indent=2)+'\n',encoding='utf-8')
    args.variants.write_text(header,encoding='utf-8')
    args.evidence.write_text(json.dumps(evidence,indent=2)+'\n',encoding='utf-8')
    print(f"Extracted {len(catalog['troops'])} troops and {len(VARIANTS)} retail variant profiles")

if __name__=='__main__':main()
