#!/usr/bin/env python3
import argparse
import re
from pathlib import Path
from capstone import CS_ARCH_X86, CS_MODE_32, Cs

XMV_VA = 0x00255620
XMV_RAW = 0x00246000
XMV_RAW_SIZE = 0x00027F84
XMV_VIRTUAL_SIZE = 0x00027F94


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("xbe", type=Path)
    parser.add_argument("generated_c", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    xbe = args.xbe.read_bytes()
    source = args.generated_c.read_text(encoding="utf-8")
    pattern = re.compile(r"Original: 0x([0-9A-Fa-f]+) - 0x([0-9A-Fa-f]+)")
    functions = []
    for start_text, end_text in pattern.findall(source):
        start, end = int(start_text, 16), int(end_text, 16)
        if XMV_VA <= start < end <= XMV_VA + XMV_VIRTUAL_SIZE:
            functions.append((start, end))
    decoder = Cs(CS_ARCH_X86, CS_MODE_32)
    decoder.detail = True
    relocations = set()
    for start, end in functions:
        raw = XMV_RAW + start - XMV_VA
        for instruction in decoder.disasm(xbe[raw:raw + end - start], start):
            for offset, size in ((instruction.disp_offset, instruction.disp_size),
                                 (instruction.imm_offset, instruction.imm_size)):
                if size != 4:
                    continue
                value = int.from_bytes(instruction.bytes[offset:offset + 4], "little")
                if XMV_VA <= value < XMV_VA + XMV_VIRTUAL_SIZE:
                    relocations.add(instruction.address - XMV_VA + offset)
    def inside_function(offset: int) -> bool:
        address = XMV_VA + offset
        return any(start <= address < end for start, end in functions)
    for offset in range(0, XMV_RAW_SIZE - 3, 4):
        value = int.from_bytes(xbe[XMV_RAW + offset:XMV_RAW + offset + 4], "little")
        if (not inside_function(offset) and
                XMV_VA <= value < XMV_VA + XMV_VIRTUAL_SIZE):
            relocations.add(offset)
    ordered = sorted(relocations)
    lines = [
        "/* Generated by generate_xmv_relocations.py from the retail XBE. */",
        f"/* {len(functions)} functions, {len(ordered)} internal relocations. */",
    ]
    for index in range(0, len(ordered), 8):
        lines.append("    " + ", ".join(f"0x{value:08X}u" for value in ordered[index:index + 8]) + ",")
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {len(ordered)} relocations from {len(functions)} functions to {args.output}")


if __name__ == "__main__":
    main()