"""Exercise production release menu lifecycle with isolated guest memory."""
from pathlib import Path
import subprocess,tempfile
ROOT=Path(__file__).resolve().parents[2]
source='\n#include <assert.h>\n#include <stdio.h>\n#include <windows.h>\n#include "recomp_options_menu.c"\nstatic unsigned char memory[0x800000];\nptrdiff_t g_xbox_mem_offset;\nstatic uint32_t heap=0x100000,allocated,freed;static int fail;\nuint32_t recomp_title_heap_allocate(uint32_t n){if(fail)return 0;uint32_t a=heap;heap+=n;++allocated;return a;}\nvoid recomp_title_heap_free(uint32_t p){assert(p>=0x100000 && p<heap);++freed;}\nvoid recomp_options_cancel_edit(void){}\nvoid recomp_options_begin_edit(void){}\nuint32_t recomp_options_apply(void){return 0;}\nint recomp_options_adjust(uint32_t h,int d){return 0;}\nconst char *recomp_options_label(uint32_t h){return 0;}\nvoid recomp_controls_close(void){}\nvoid recomp_controls_open(void){}\nunsigned recomp_controls_count(void){return 6;}\nuint32_t recomp_controls_input(unsigned r,unsigned i,unsigned e){return 0;}\nconst char *recomp_controls_label(uint32_t h){return 0;}\nstatic void menu(uint32_t m,uint32_t name){memset(memory+m,0,0x80);w32(m+0x54,name);w32(m+0x44,1);w32(m+4,allocate_item(MENU_SHELL_OPTIONS_HASH,14));}\nint main(void){\n g_xbox_mem_offset=(ptrdiff_t)memory;uint32_t main=0x10000,opt=0x11000,owner=0x20000;\n menu(main,MENU_MAIN_HASH);insert_entry(main);unsigned n=u32(main+0x44);\n assert(item_hash(main,n-2)==RECOMP_ACK_MENU_HASH && item_hash(main,n-1)==RECOMP_QUIT_HASH);\n insert_entry(main);assert(u32(main+0x44)==n);\n menu(opt,MENU_SHELL_OPTIONS_HASH);uint32_t original=u32(opt+4);\n w32(owner+0x3eb8,main);w32(main+0x48,n-2);recomp_options_menu_transition(owner,opt);\n assert(recomp_acknowledgements_active() && u32(opt+0x44)==16 && u32(opt+0x48)==15);\n for(unsigned i=0;i<4;++i){assert(recomp_options_input_checkpoint(opt,i,1)==1);assert(u32(opt+0x48)==15);}\n assert(recomp_options_input_checkpoint(opt,5,1)==2);assert(recomp_options_input_checkpoint(opt,4,1)==0);\n uint32_t brush=0x30000;w32(brush+0x40,RECOMP_ACK_ROW);MEMF(0x7AB600)=2;MEMF(0x7AB5FC)=3;\n recomp_ack_text_scale(brush,0,1);assert(MEM32(0x7AB5F0)==0x80FFFFFFu);assert(MEMF(0x7AB600)>1.19f && MEMF(0x7AB600)<1.21f);\n w32(owner+0x3eb8,opt);recomp_options_menu_transition(owner,main);\n assert(!recomp_acknowledgements_active() && u32(opt+4)==original && u32(opt+0x44)==1 && freed==16);\n fail=1;w32(owner+0x3eb8,main);recomp_options_menu_transition(owner,opt);\n assert(!recomp_acknowledgements_active() && u32(opt+4)==original);fail=0;\n w32(main+0x48,n-1);assert(recomp_options_input_checkpoint(main,5,4)==0);\n MSG msg;assert(!PeekMessage(&msg,NULL,WM_QUIT,WM_QUIT,PM_REMOVE));\n assert(recomp_options_input_checkpoint(main,5,1)==1);assert(PeekMessage(&msg,NULL,WM_QUIT,WM_QUIT,PM_REMOVE));\n puts("PASS: main ordering/idempotence, static acknowledgements/back, font sizing, restoration, allocation failure and quit");\n}\n'
with tempfile.TemporaryDirectory(prefix='merc-release-menu-') as folder:
 d=Path(folder);(d/'test.c').write_text(source);exe=d/'test.exe'
 subprocess.run(['C:/MinGW/bin/gcc.exe','-std=c11','-O2','-I'+str(ROOT/'ports/mercenaries/src'),'-I'+str(ROOT/'src/input'),'-I'+str(ROOT/'src'),'-I'+str(ROOT/'include'),str(d/'test.c'),'-o',str(exe),'-luser32','-lm'],check=True)
 subprocess.run([str(exe)],check=True)
